export * from './OPDPatientIcon';
export * from './DashboardIcon';
export * from './LabIcon';
export * from './IPDAdmissionIcon'
export * from './WardManagementIcon'
export * from "./IPDPatientsIcon"
export * from "./HouseKeepingBeds"
export * from "./SettingsIcon"
export * from "./SortIcon"
export * from "./ProfileCalendarIcon"
export * from "./Ellipse"
export * from "./MoneyIcon"
export * from "./ProtectIcon"
export * from "./WarningIcon"
export * from "./HealthBoxIcon"
export * from "./ShareIconEnable"
export * from "./ShareIconDisable"
export * from "./BusinessReportIcon"
