import { Product, Category, Collection, ProductReview } from '@/types/product.types';
import { Order } from '@/types/order.types';
import { AdminCustomer, AdminUser, InventoryItem, StockHistoryItem, Coupon, CMSBanner, AppNotification } from '@/types/admin.types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'Celeste 1.50 ct Solitaire Diamond Ring',
    slug: 'celeste-solitaire-diamond-ring',
    sku: 'JWL-RNG-001',
    description: 'An iconic symbol of eternal commitment. Featuring an ethereal 1.50 ct brilliant-cut round diamond clasped in a platinum 6-prong cathedral setting, flanked by micro-pave diamonds along the shank.',
    shortDescription: '1.50 Carat IGI Certified Solitaire in 950 Platinum',
    price: 185000,
    comparePrice: 220000,
    discountPercentage: 16,
    rating: 4.9,
    reviewsCount: 42,
    category: 'Rings',
    subcategory: 'Solitaire Rings',
    collection: 'Celeste Celestial Diamonds',
    gender: 'Women',
    metal: 'Platinum',
    purity: '950 Platinum',
    weight: 4.8,
    gemstone: 'Diamond',
    stoneWeight: 1.50,
    diamondClarity: 'VVS1',
    diamondColor: 'E',
    certification: 'IGI Certified Natural Diamond & BIS Hallmarked',
    stock: 8,
    lowStockThreshold: 3,
    isAvailable: true,
    images: [
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isBestSeller: true,
    sizes: ['10', '12', '14', '16', '18'],
    tags: ['solitaire', 'platinum', 'wedding', 'certified'],
    createdAt: '2026-01-15',
    status: 'active',
  },
  {
    id: 'prod-2',
    name: 'The Royal Nizam 22K Kundan Choker Necklace',
    slug: 'royal-nizam-kundan-choker-necklace',
    sku: 'JWL-NCK-002',
    description: 'Inspired by the opulent court of the Nizams of Hyderabad. Meticulously handcrafted in 22K hallmarked gold with uncut polki diamonds, lustrous south sea pearls, and Colombian emerald droplets.',
    shortDescription: 'Imperial 22K Gold & Polki Choker with Emerald Droplets',
    price: 345000,
    comparePrice: 380000,
    discountPercentage: 9,
    rating: 5.0,
    reviewsCount: 18,
    category: 'Necklaces',
    subcategory: 'Royal Chokers',
    collection: 'The Royal Nizam Collection',
    gender: 'Women',
    metal: 'Yellow Gold',
    purity: '22K',
    weight: 58.4,
    gemstone: 'Emerald',
    stoneWeight: 12.0,
    certification: 'BIS 916 Hallmarked & Certified Gemological Report',
    stock: 3,
    lowStockThreshold: 2,
    isAvailable: true,
    images: [
      'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isNewArrival: true,
    isTrending: true,
    tags: ['choker', 'bridal', '22k', 'emerald', 'kundan'],
    createdAt: '2026-01-20',
    status: 'active',
  },
  {
    id: 'prod-3',
    name: 'Imperial Cascading Diamond Jhumkas',
    slug: 'imperial-cascading-diamond-jhumkas',
    sku: 'JWL-ERR-003',
    description: 'Traditional bell silhouette reinvented with contemporary diamond brilliance. Features floral stud motifs with cascading diamond drops set in 18K yellow gold.',
    shortDescription: 'Heritage Jhumkas with 2.80 Carats Brilliant Diamonds',
    price: 142000,
    comparePrice: 165000,
    discountPercentage: 14,
    rating: 4.8,
    reviewsCount: 31,
    category: 'Earrings',
    subcategory: 'Traditional Jhumkas',
    collection: 'Vedic Temple Heritage',
    gender: 'Women',
    metal: 'Yellow Gold',
    purity: '18K',
    weight: 16.2,
    gemstone: 'Diamond',
    stoneWeight: 2.80,
    diamondClarity: 'VS1',
    diamondColor: 'F',
    certification: 'BIS Hallmarked & SGL Diamond Certified',
    stock: 12,
    lowStockThreshold: 4,
    isAvailable: true,
    images: [
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isBestSeller: true,
    tags: ['earrings', 'jhumka', 'diamonds', 'festive'],
    createdAt: '2026-02-01',
    status: 'active',
  },
  {
    id: 'prod-4',
    name: 'Luminescence 18K Rose Gold Tennis Bracelet',
    slug: 'luminescence-rose-gold-tennis-bracelet',
    sku: 'JWL-BRC-004',
    description: 'A seamless, continuous river of 5.50 carats round brilliant diamonds hand-set in flexible 18K rose gold bezels with a secure double-safety clasp.',
    shortDescription: '5.50 Carats All-Diamond Tennis Line in 18K Rose Gold',
    price: 215000,
    comparePrice: 245000,
    discountPercentage: 12,
    rating: 4.9,
    reviewsCount: 27,
    category: 'Bracelets',
    subcategory: 'Tennis Bracelets',
    collection: 'Modern Minimalist Gold',
    gender: 'Women',
    metal: 'Rose Gold',
    purity: '18K',
    weight: 12.5,
    gemstone: 'Diamond',
    stoneWeight: 5.50,
    diamondClarity: 'VVS2',
    diamondColor: 'G',
    certification: 'IGI Diamond Certified & 18K Hallmarked',
    stock: 6,
    lowStockThreshold: 2,
    isAvailable: true,
    images: [
      'https://images.unsplash.com/photo-1611591475829-063991207604?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isTrending: true,
    sizes: ['6.5 inch', '7.0 inch', '7.5 inch'],
    tags: ['bracelet', 'tennis', 'diamonds', 'rose-gold'],
    createdAt: '2026-02-05',
    status: 'active',
  },
  {
    id: 'prod-5',
    name: 'Mayur 22K Gold Antique Temple Kadas (Pair)',
    slug: 'mayur-antique-temple-kadas',
    sku: 'JWL-BNG-005',
    description: 'Handcrafted pair of heavy 22K temple bangles embossed with peacock and floral filigree, finished with antique red patina and screw-locking hinges.',
    shortDescription: 'Pair of Heavy 22K Antique Kadas (48 grams)',
    price: 298000,
    comparePrice: 320000,
    discountPercentage: 7,
    rating: 4.9,
    reviewsCount: 19,
    category: 'Bangles',
    subcategory: 'Traditional Gold Kadas',
    collection: 'Vedic Temple Heritage',
    gender: 'Women',
    metal: 'Yellow Gold',
    purity: '22K',
    weight: 48.0,
    gemstone: 'Ruby',
    stoneWeight: 1.20,
    certification: 'BIS 916 Government Hallmarked',
    stock: 4,
    lowStockThreshold: 2,
    isAvailable: true,
    images: [
      'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
    ],
    isBestSeller: true,
    sizes: ['2.4', '2.6', '2.8'],
    tags: ['bangles', 'kada', '22k', 'temple'],
    createdAt: '2026-02-10',
    status: 'active',
  },
  {
    id: 'prod-6',
    name: 'Vanguard Men\'s Platinum & Solid Gold Kada',
    slug: 'vanguard-mens-platinum-solid-gold-kada',
    sku: 'JWL-MEN-006',
    description: 'Cast in 950 pure platinum with an inner core of 22K yellow gold. Designed with bevelled brushed edges and engraved with fine diamond highlights for distinguished men.',
    shortDescription: 'Dual Tone Platinum & 22K Solid Heavy Kada for Men',
    price: 195000,
    comparePrice: 225000,
    discountPercentage: 13,
    rating: 4.9,
    reviewsCount: 22,
    category: 'Men\'s Jewellery',
    subcategory: 'Heavy Kadas & Cuffs',
    collection: 'Modern Minimalist Gold',
    gender: 'Men',
    metal: 'Platinum',
    purity: '950 Platinum',
    weight: 38.5,
    gemstone: 'Diamond',
    stoneWeight: 0.45,
    certification: 'Pt950 Certified & BIS Hallmarked',
    stock: 5,
    lowStockThreshold: 2,
    isAvailable: true,
    images: [
      'https://images.unsplash.com/photo-1622398925373-3f9171e275f5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
    ],
    isFeatured: true,
    isTrending: true,
    sizes: ['Free Size (Adjustable)', 'M', 'L'],
    tags: ['men', 'kada', 'platinum', 'gold'],
    createdAt: '2026-02-12',
    status: 'active',
  },
  {
    id: 'prod-7',
    name: 'Aura Rose Gold & South Sea Pearl Pendant',
    slug: 'aura-rose-gold-south-sea-pearl-pendant',
    sku: 'JWL-NCK-007',
    description: 'An immaculate 12mm golden South Sea cultured pearl cradled in an 18K rose gold diamond-encrusted petal frame, suspended from a matching delicate chain.',
    shortDescription: 'Golden South Sea Pearl & Diamonds in 18K Rose Gold',
    price: 78000,
    comparePrice: 89000,
    discountPercentage: 12,
    rating: 4.7,
    reviewsCount: 15,
    category: 'Necklaces',
    subcategory: 'Solitaire & Diamond Pendants',
    collection: 'Aura Rose Gold & Pearls',
    gender: 'Women',
    metal: 'Rose Gold',
    purity: '18K',
    weight: 6.2,
    gemstone: 'Pearl',
    stoneWeight: 0.35,
    certification: 'BIS Hallmarked & Cultured Pearl Guarantee',
    stock: 15,
    lowStockThreshold: 5,
    isAvailable: true,
    images: [
      'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=800&q=80',
    ],
    isNewArrival: true,
    tags: ['pendant', 'pearl', 'rose-gold', 'daily'],
    createdAt: '2026-02-18',
    status: 'active',
  },
  {
    id: 'prod-8',
    name: 'Eternal Solitaire Diamond Stud Earrings (1.0 ct tw)',
    slug: 'eternal-solitaire-diamond-stud-earrings',
    sku: 'JWL-ERR-008',
    description: 'Classic 4-prong basket solitaire stud earrings. Two matching 0.50 ct brilliant-cut round diamonds set in 18K white gold with secure screw backs.',
    shortDescription: '1.00 Carat Total Weight Solitaire Studs in 18K White Gold',
    price: 92000,
    comparePrice: 105000,
    discountPercentage: 12,
    rating: 5.0,
    reviewsCount: 54,
    category: 'Earrings',
    subcategory: 'Diamond & Gold Studs',
    collection: 'Celeste Celestial Diamonds',
    gender: 'Women',
    metal: 'White Gold',
    purity: '18K',
    weight: 2.8,
    gemstone: 'Diamond',
    stoneWeight: 1.00,
    diamondClarity: 'VVS2',
    diamondColor: 'F',
    certification: 'IGI Certified Natural Diamonds',
    stock: 20,
    lowStockThreshold: 5,
    isAvailable: true,
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=800&q=80',
    ],
    isBestSeller: true,
    tags: ['studs', 'solitaire', 'diamonds', 'gift'],
    createdAt: '2026-02-20',
    status: 'active',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-rings',
    name: 'Rings',
    slug: 'rings',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=600&q=80',
    description: 'Solitaire, engagement, wedding bands, and cocktail rings cast in pure gold and platinum.',
    status: 'active',
    sortOrder: 1,
    productCount: 142,
  },
  {
    id: 'cat-earrings',
    name: 'Earrings',
    slug: 'earrings',
    image: 'https://images.unsplash.com/photo-1630019852942-f89202989a59?auto=format&fit=crop&w=600&q=80',
    description: 'From minimal studs to grand chandelier jhumkas and diamond hoops.',
    status: 'active',
    sortOrder: 2,
    productCount: 118,
  },
  {
    id: 'cat-necklaces',
    name: 'Necklaces',
    slug: 'necklaces',
    image: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=600&q=80',
    description: 'Imperial chokers, diamond pendants, mangalsutras, and royal bridal haars.',
    status: 'active',
    sortOrder: 3,
    productCount: 96,
  },
  {
    id: 'cat-bracelets',
    name: 'Bracelets',
    slug: 'bracelets',
    image: 'https://images.unsplash.com/photo-1611591475829-063991207604?auto=format&fit=crop&w=600&q=80',
    description: 'Diamond tennis bracelets, flexible cuffs, and charm link chains.',
    status: 'active',
    sortOrder: 4,
    productCount: 64,
  },
  {
    id: 'cat-bangles',
    name: 'Bangles',
    slug: 'bangles',
    image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=600&q=80',
    description: 'Traditional 22K hallmarked kadas, eternity diamond bangles, and bridal sets.',
    status: 'active',
    sortOrder: 5,
    productCount: 52,
  },
];

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: 'col-1',
    name: 'The Royal Nizam Collection',
    slug: 'nizam',
    banner: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1200&q=80',
    description: 'Regal polki heirlooms crafted with Colombian emeralds and 22K heritage gold.',
    productsCount: 28,
    status: 'active',
    isFeatured: true,
  },
  {
    id: 'col-2',
    name: 'Celeste Celestial Diamonds',
    slug: 'celeste',
    banner: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=80',
    description: 'Precision-cut certified solitaire diamonds radiating astronomical brilliance.',
    productsCount: 34,
    status: 'active',
    isFeatured: true,
  },
  {
    id: 'col-3',
    name: 'Vedic Temple Heritage',
    slug: 'temple',
    banner: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=1200&q=80',
    description: 'Sacred architectural jewellery embossed with deities, peacocks, and temple nakshi.',
    productsCount: 42,
    status: 'active',
    isFeatured: true,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    orderNumber: 'JWL-2026-9041',
    createdAt: '2026-03-01T14:30:00Z',
    customer: {
      id: 'cust-1',
      name: 'Aarav Sharma',
      email: 'aarav.sharma@example.com',
      phone: '+91 9820011223',
    },
    items: [
      {
        id: 'oi-1',
        productId: 'prod-1',
        name: 'Celeste 1.50 ct Solitaire Diamond Ring',
        sku: 'JWL-RNG-001',
        image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=200&q=80',
        metal: 'Platinum',
        purity: '950 Platinum',
        size: '14',
        unitPrice: 185000,
        quantity: 1,
        totalPrice: 185000,
      },
    ],
    subtotal: 185000,
    discount: 5000,
    couponCode: 'JEWELO5000',
    tax: 5400,
    shippingCharge: 0,
    grandTotal: 185400,
    paymentMethod: 'UPI',
    paymentStatus: 'PAID',
    orderStatus: 'SHIPPED',
    shippingAddress: {
      fullName: 'Aarav Sharma',
      phone: '+91 9820011223',
      addressLine1: 'B-402, Imperial Heights, Lokhandwala',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400053',
      isDefault: true,
      type: 'home',
    },
    estimatedDeliveryDate: '2026-03-06',
    trackingNumber: 'BLUEDART-EXP-992019',
    timeline: [
      {
        status: 'CONFIRMED',
        title: 'Order Confirmed',
        description: 'Payment successfully received via UPI (HDFC Bank).',
        timestamp: '2026-03-01 14:32',
        isCompleted: true,
      },
      {
        status: 'PROCESSING',
        title: 'Custom Hallmarking & Quality Check',
        description: 'Hand-inspected under gemological loupe and packaged in tamper-proof seal.',
        timestamp: '2026-03-02 11:15',
        isCompleted: true,
      },
      {
        status: 'SHIPPED',
        title: 'Dispatched via Insured Transit',
        description: 'Consignment handed to BlueDart Apex Express Courier.',
        timestamp: '2026-03-03 17:40',
        location: 'Mumbai Central Hub',
        isCompleted: true,
      },
      {
        status: 'OUT_FOR_DELIVERY',
        title: 'Out For Delivery',
        description: 'Dedicated courier agent with OTP delivery verification.',
        timestamp: 'Estimated 2026-03-06',
        isCompleted: false,
      },
    ],
  },
  {
    id: 'ord-1002',
    orderNumber: 'JWL-2026-9042',
    createdAt: '2026-02-26T09:15:00Z',
    customer: {
      id: 'cust-2',
      name: 'Priyanka Singhania',
      email: 'priyanka.s@example.com',
      phone: '+91 9811099887',
    },
    items: [
      {
        id: 'oi-2',
        productId: 'prod-4',
        name: 'Luminescence 18K Rose Gold Tennis Bracelet',
        sku: 'JWL-BRC-004',
        image: 'https://images.unsplash.com/photo-1611591475829-063991207604?auto=format&fit=crop&w=200&q=80',
        metal: 'Rose Gold',
        purity: '18K',
        size: '7.0 inch',
        unitPrice: 215000,
        quantity: 1,
        totalPrice: 215000,
      },
    ],
    subtotal: 215000,
    discount: 0,
    tax: 6450,
    shippingCharge: 0,
    grandTotal: 221450,
    paymentMethod: 'CREDIT_CARD',
    paymentStatus: 'PAID',
    orderStatus: 'DELIVERED',
    shippingAddress: {
      fullName: 'Priyanka Singhania',
      phone: '+91 9811099887',
      addressLine1: 'Villa 18, Golf Links Estates',
      city: 'New Delhi',
      state: 'Delhi',
      country: 'India',
      pincode: '110003',
      isDefault: true,
      type: 'home',
    },
    estimatedDeliveryDate: '2026-03-01',
    actualDeliveryDate: '2026-03-01',
    trackingNumber: 'BLUEDART-EXP-991823',
    timeline: [
      {
        status: 'CONFIRMED',
        title: 'Order Confirmed',
        description: 'Payment authorized.',
        timestamp: '2026-02-26 09:16',
        isCompleted: true,
      },
      {
        status: 'SHIPPED',
        title: 'Dispatched',
        description: 'In transit with secure armored courier.',
        timestamp: '2026-02-27 16:00',
        isCompleted: true,
      },
      {
        status: 'DELIVERED',
        title: 'Delivered',
        description: 'Signed for by client at door.',
        timestamp: '2026-03-01 13:45',
        isCompleted: true,
      },
    ],
  },
];

export const MOCK_ADMIN_CUSTOMERS: AdminCustomer[] = [
  {
    id: 'cust-1',
    name: 'Aarav Sharma',
    email: 'aarav.sharma@example.com',
    phone: '+91 9820011223',
    totalOrders: 4,
    totalSpent: 485000,
    status: 'active',
    createdAt: '2025-08-14',
    lastLogin: '2026-03-01',
    wishlistCount: 6,
    reviewCount: 2,
  },
  {
    id: 'cust-2',
    name: 'Priyanka Singhania',
    email: 'priyanka.s@example.com',
    phone: '+91 9811099887',
    totalOrders: 7,
    totalSpent: 920000,
    status: 'active',
    createdAt: '2025-05-10',
    lastLogin: '2026-02-28',
    wishlistCount: 11,
    reviewCount: 5,
  },
  {
    id: 'cust-3',
    name: 'Vikramaditya Roy',
    email: 'vikram.roy@example.com',
    phone: '+91 9830044556',
    totalOrders: 2,
    totalSpent: 195000,
    status: 'active',
    createdAt: '2025-11-20',
    lastLogin: '2026-02-15',
    wishlistCount: 3,
    reviewCount: 1,
  },
];

export const MOCK_ADMIN_USERS: AdminUser[] = [
  {
    id: 'usr-1',
    name: 'Devraj Oberoi',
    email: 'devraj@jewelo.com',
    phone: '+91 9900112233',
    role: 'SUPER_ADMIN',
    status: 'active',
    lastLogin: '2026-03-02 08:30',
    createdAt: '2025-01-01',
  },
  {
    id: 'usr-2',
    name: 'Ananya Deshmukh',
    email: 'ananya@jewelo.com',
    phone: '+91 9900112244',
    role: 'ADMIN',
    status: 'active',
    lastLogin: '2026-03-01 18:40',
    createdAt: '2025-03-12',
  },
  {
    id: 'usr-3',
    name: 'Karan Mehra',
    email: 'karan@jewelo.com',
    phone: '+91 9900112255',
    role: 'MANAGER',
    status: 'active',
    lastLogin: '2026-02-28 16:10',
    createdAt: '2025-06-20',
  },
  {
    id: 'usr-4',
    name: 'Meera Nair',
    email: 'meera@jewelo.com',
    phone: '+91 9900112266',
    role: 'STAFF',
    status: 'active',
    lastLogin: '2026-03-01 10:20',
    createdAt: '2025-09-05',
  },
];

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-1',
    productId: 'prod-1',
    productName: 'Celeste 1.50 ct Solitaire Diamond Ring',
    sku: 'JWL-RNG-001',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=200&q=80',
    category: 'Rings',
    currentStock: 8,
    reservedStock: 2,
    availableStock: 6,
    threshold: 3,
    status: 'in_stock',
    lastUpdated: '2026-03-01',
  },
  {
    id: 'inv-2',
    productId: 'prod-2',
    productName: 'The Royal Nizam 22K Kundan Choker',
    sku: 'JWL-NCK-002',
    image: 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?auto=format&fit=crop&w=200&q=80',
    category: 'Necklaces',
    currentStock: 3,
    reservedStock: 1,
    availableStock: 2,
    threshold: 2,
    status: 'low_stock',
    lastUpdated: '2026-02-28',
  },
  {
    id: 'inv-3',
    productId: 'prod-5',
    productName: 'Mayur 22K Gold Antique Temple Kadas',
    sku: 'JWL-BNG-005',
    image: 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?auto=format&fit=crop&w=200&q=80',
    category: 'Bangles',
    currentStock: 1,
    reservedStock: 1,
    availableStock: 0,
    threshold: 2,
    status: 'out_of_stock',
    lastUpdated: '2026-02-25',
  },
];

export const MOCK_STOCK_HISTORY: StockHistoryItem[] = [
  {
    id: 'sh-1',
    date: '2026-03-01 14:35',
    productId: 'prod-1',
    productName: 'Celeste 1.50 ct Solitaire Diamond Ring',
    quantity: -1,
    type: 'sale',
    reason: 'Customer Order #JWL-2026-9041',
    userName: 'Automated System',
  },
  {
    id: 'sh-2',
    date: '2026-02-27 11:20',
    productId: 'prod-1',
    productName: 'Celeste 1.50 ct Solitaire Diamond Ring',
    quantity: 5,
    type: 'addition',
    reason: 'New Production Batch from Vault',
    userName: 'Karan Mehra',
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 'cp-1',
    code: 'JEWELO25',
    discountType: 'percentage',
    discountValue: 25,
    minOrder: 50000,
    maxDiscount: 20000,
    usageLimit: 500,
    usageCount: 142,
    perCustomerLimit: 1,
    startDate: '2026-02-01',
    endDate: '2026-04-30',
    status: 'active',
  },
  {
    id: 'cp-2',
    code: 'SOLITAIRE5000',
    discountType: 'fixed',
    discountValue: 5000,
    minOrder: 100000,
    usageLimit: 200,
    usageCount: 88,
    perCustomerLimit: 1,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    status: 'active',
  },
];

export const MOCK_BANNERS: CMSBanner[] = [
  {
    id: 'ban-1',
    title: 'Spring Symphony 2026',
    subtitle: 'Timeless 22K Hallmarked Gold & Ethereal Solitaires',
    desktopImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1600&q=80',
    mobileImage: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=80',
    ctaText: 'Explore New In',
    ctaUrl: '/products?tag=new-arrivals',
    startDate: '2026-01-01',
    endDate: '2026-06-30',
    sortOrder: 1,
    status: 'published',
    placement: 'hero',
  },
  {
    id: 'ban-2',
    title: 'The Solitaire Gala',
    subtitle: 'Zero Making Charges on All Solitaire Creations',
    desktopImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1600&q=80',
    mobileImage: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=80',
    ctaText: 'Discover Solitaires',
    ctaUrl: '/products?category=rings',
    startDate: '2026-02-15',
    endDate: '2026-04-15',
    sortOrder: 2,
    status: 'published',
    placement: 'promo',
  },
];

export const MOCK_REVIEWS: ProductReview[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    productName: 'Celeste 1.50 ct Solitaire Diamond Ring',
    customerName: 'Aarav Sharma',
    rating: 5,
    title: 'Surpassed every expectation. Truly breathtaking!',
    comment: 'I proposed with this solitaire in Switzerland and my fiancee was speechless. The clarity of the diamond caught every reflection of light. The IGI certification provided complete peace of mind.',
    createdAt: '2026-02-20',
    status: 'approved',
    verifiedPurchase: true,
  },
  {
    id: 'rev-2',
    productId: 'prod-2',
    productName: 'The Royal Nizam 22K Kundan Choker',
    customerName: 'Priyanka Singhania',
    rating: 5,
    title: 'Heirloom quality piece for my wedding',
    comment: 'The craftsmanship on the polki and emerald droplets is museum grade. Weight feels substantial and the gold hallmark is pristine.',
    createdAt: '2026-02-15',
    status: 'approved',
    verifiedPurchase: true,
  },
  {
    id: 'rev-3',
    productId: 'prod-4',
    customerName: 'Natasha Kapoor',
    rating: 4,
    title: 'Beautiful daily luxury',
    comment: 'The rose gold complements Indian skin tones gorgeously. Very smooth setting that never catches on silks.',
    createdAt: '2026-02-28',
    status: 'pending',
    verifiedPurchase: true,
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'New High-Value Order Placed',
    message: 'Order #JWL-2026-9041 received for ₹1,85,400 via UPI.',
    type: 'order',
    createdAt: '10 mins ago',
    isRead: false,
    link: '/admin/orders',
    targetRole: 'admin',
  },
  {
    id: 'notif-2',
    title: 'Low Stock Alert',
    message: 'The Royal Nizam 22K Kundan Choker has reached 2 available units.',
    type: 'stock',
    createdAt: '1 hour ago',
    isRead: false,
    link: '/admin/inventory',
    targetRole: 'admin',
  },
  {
    id: 'notif-3',
    title: 'Order Shipped',
    message: 'Your order #JWL-2026-9041 is on its way via BlueDart Insured Transit.',
    type: 'order',
    createdAt: '3 hours ago',
    isRead: false,
    link: '/orders',
    targetRole: 'customer',
  },
];
